services:
  - type: web
    name: sql-gemini-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
    autoDeploy: true
